### PR TITLE
Base r

### PR DESCRIPTION
**Pull request by jkaupp**
I was really impressed with the work, and it was far better than any kludgy attempt I ever made. I made the conversion from `tidyverse` code to `base` in order to reduce the dependencies and to move some helper/utility functions.   Let me know if you have any questions!

* Clean R CMD Check.

### CODE REVIEW

**Comment by davidsjoberg** [comment]
Hi @jkaupp I missed this PR. Thank you!! I really think the switch to `base` is a better way to do it!

However, since I was ignorant enough to have missed this PR I have some conflicting commits between the version you worked on and the current master branch. 

I will look into your comments and maybe you can have a second look after I've tried to resolve the merge?

Again, big thanks!!

**Comment by jkaupp** [comment]
No worries about the timing, that's the beauty of GitHub you get to it when you can! I think this is a great addition to the ggplot2 ecosystem and I'm happy to help/contribute.  The primary reason I did this was to make the dependency footprint smaller.

Most of the conflicts may be due to changes in documentation and some functions that were externalized (for ease of use in `lapply`).  I'd be glad to talk about any questions/issues and help once you end up merging.

**Comment by davidsjoberg** [comment]
I read through your PR. Great work. I merge it with master!

**Comment by davidsjoberg** [comment]
I get incorrect plots with your latest branch. Reprex (have installed your branch as `ggstream`)

``` r
library(ggplot2)
library(ggstream)
ggplot(mtcars, aes(qsec, drat, fill = factor(cyl))) +
  geom_stream(method = "density")
```



<sup>Created on 2020-06-06 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

I'm not comfortable enough in base R to do an error search. Maybe you want to take another look? If you don't have time I stay within tidyverse a while longer since that's what I know a lot better :)

**Comment by jkaupp** [comment]
I'll take a look and track down the error. Looks like an ordering problem at first glance.

**Comment by jkaupp** [comment]
So the issue is something that happens in the final pieces of StatStreamDensity.  This piece of code in your master branch

```
suppressWarnings(data %>%
    dplyr::select(-"x", -"y") %>%
    dplyr::distinct() %>%
    dplyr::left_join(.per_panel, by = c("group", "PANEL"))
```
`dplyr::left_join` nicely preserves the order in both data sets.  `base::merge` isn't as forgiving.  After double checking our outputs were identical from all steps, I finally remembered out how to properly order it after the merge.

``` r
library(ggplot2)
library(ggstream)

ggplot(mtcars, aes(qsec, drat, fill = factor(cyl))) +
  geom_stream(method = "density")
```

**Comment by davidsjoberg** [comment]
Awesome! One last thing needs to fixed before I replace the tidyverse dependencies. The `method = "raw"` version is significantly slower in the `base` implementation. I can't see where is bottleneck is happening. Would you know. Maybe:

```
inrange_out <- do.call(rbind, apply(df, 1, build_range, inside_range = inside_local_range))
```

is alot slower than

```
.inrange_out <- purrr::pmap_dfr(.df, ~{
    .xlr <- inside_local_range[inside_local_range >= ..1 & inside_local_range <= ..3]
    dplyr::tibble(x = .xlr,
           y = points_on_line(.xlr, ..1, ..2, ..3, ..4))
  })
?
```

**Comment by jkaupp** [comment]
I'll profile that piece of code to see where the bottleneck is and try to see what I can do to improve the runtime

**Comment by jkaupp** [comment]
The slowdown was being caused by improper ordering in the initial construction of the group mean y values.  I neglected to order the data frame prior to assignment which messed up the order of the data.  This caused the slowdown in drawing the plot as the paths were overlapping.

`apply` vs `pmap` see this [comparison](https://rpubs.com/wch/200398), has some interesting methods for rowwise operations & speed.

``` r
library(ggplot2)
library(ggstream)

ggplot(mtcars, aes(qsec, drat, fill = factor(cyl))) +
  geom_stream(method = "raw")
```

**Pull request closed without merging**
